Name:           perl-Net-Dict
Version:        2.13
Release:        1%{?dist}
Summary:        Client API for accessing dictionary servers (RFC 2229)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-Dict/
Source0:        http://www.cpan.org/modules/by-module/Net/Net-Dict-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(AppConfig::Std)
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(AppConfig::Std)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Net::Dict is a perl class for looking up words and their definitions on
network dictionary servers. Net::Dict provides a simple DICT client API for
the network protocol described in RFC2229. Quoting from that RFC:

%prep
%setup -q -n Net-Dict-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dict META.json README tkdict
%{perl_vendorlib}/*
%{_mandir}/man1/*
%{_mandir}/man3/*
/usr/bin/dict
/usr/bin/tkdict

%changelog
* Wed Jan 15 2014 DanielC 2.13-1
- Specfile autogenerated by cpanspec 1.78.
